version: '3.8'

services:
  db:
    image: postgres:15 # Use a specific version
    container_name: nautmanager_db
    restart: always
    environment:
      POSTGRES_DB: nautmanager_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password # Change in production!
    ports:
      - "5436:5432" # Map host port 5436 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U user -d nautmanager_dev"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  postgres_data:
    driver: local 